services:
  app:
    build: .
    container_name: signboard_app
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./config.inf:/app/config.inf
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - REMOTE_ACCESS_ENABLED=false
    restart: always

  # 未來可擴充 rclone 定時備份容器
  # backup:
  #   image: rclone/rclone
  #   ...
